package mw.base.mybatis.dao.mapper;

import java.util.List;
import mw.base.mybatis.dao.model.TLoginLog;
import mw.base.mybatis.dao.model.TLoginLogExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    int countByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    int deleteByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    @Delete({
        "delete from t_login_log",
        "where login_log_id = #{loginLogId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer loginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    @Insert({
        "insert into t_login_log (login_log_id, user_id, ",
        "ip, login_datetime)",
        "values (#{loginLogId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{ip,jdbcType=VARCHAR}, #{loginDatetime,jdbcType=TIMESTAMP})"
    })
    int insert(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    int insertSelective(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    List<TLoginLog> selectByExample(TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    @Select({
        "select",
        "login_log_id, user_id, ip, login_datetime",
        "from t_login_log",
        "where login_log_id = #{loginLogId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TLoginLog selectByPrimaryKey(Integer loginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") TLoginLog record, @Param("example") TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    int updateByExample(@Param("record") TLoginLog record, @Param("example") TLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    int updateByPrimaryKeySelective(TLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_log
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    @Update({
        "update t_login_log",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "login_datetime = #{loginDatetime,jdbcType=TIMESTAMP}",
        "where login_log_id = #{loginLogId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TLoginLog record);
}