package mw.base.mybatis.dao.model;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.credits
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    private Integer credits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_visit
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    private Date lastVisit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_ip
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    private String lastIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.credits
     *
     * @return the value of t_user.credits
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.credits
     *
     * @param credits the value for t_user.credits
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_visit
     *
     * @return the value of t_user.last_visit
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public Date getLastVisit() {
        return lastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_visit
     *
     * @param lastVisit the value for t_user.last_visit
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public void setLastVisit(Date lastVisit) {
        this.lastVisit = lastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_ip
     *
     * @return the value of t_user.last_ip
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_ip
     *
     * @param lastIp the value for t_user.last_ip
     *
     * @mbggenerated Fri Mar 30 13:10:04 CST 2018
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }
}